### ISSUE TITLE
configuration?

### ISSUE THREAD

**Issue by TekExplorer** [EdyTheCow/pterodactyl-docker#2]
how do i configure my node? should i let cloudflare proxy my node.domain or dns only? ghow about the panel?

**Comment by EdyTheCow** [comment]
> how do i configure my node? should i let cloudflare proxy my node.domain or dns only? ghow about the panel?

Hey,
I'm in progress of redoing the whole setup and guide making as easy as possible to set it up for anyone interested. As of right now the setup is unusable. To answer your question, if you're running daemon and panel on the same server you can put both daemon and panel subdomains under CF's proxy. However, if you're daemon is running on a different server, you'll have to expose node's IP. The panel's domain can be always under proxy.

**Comment by EdyTheCow** [comment]
@TekExplorer docker-compose.yml and the guide has been updated

**Comment by TekExplorer** [comment]
Interesting, I actually already got it working
