### ISSUE TITLE
Blocked by CORS Policy

### ISSUE THREAD

**Issue by TekExplorer** [EdyTheCow/pterodactyl-docker#5]
![87237092-c042e200-c3bf-11ea-8450-486901ff4fb1](https://user-images.githubusercontent.com/30291302/87237126-4e1ecd00-c3c0-11ea-8bc5-8aee0b0fa509.png)

the person im helping got this. what needs to be changed to fix this?

i somehow got it working on my system, so if you want to see my toml ill give it. its kinda over-complicated though

edited to remove domain
deleted edits to erase domain further

**Comment by EdyTheCow** [comment]
https://github.com/EdyTheCow/pterodactyl-docker/blob/master/compose/docker-compose.yml#L66
This and below labels solve the issue.

**Comment by TekExplorer** [comment]
its in there: [HASTEBIN](https://hasteb.in/uxewades.http)

**Comment by TekExplorer** [comment]
i believe i fixed it by using accessControlAllowOrigin**_List_** instead
not sure why, but it fixed mine when i was troubleshooting before (hurts my brain remembering it)

**Comment by EdyTheCow** [comment]
I've used current setup multiple times now when installing the panel and I didn't face the issue you described above.

**Comment by TekExplorer** [comment]
Odd, I will have him check other things first before testing my solution... Hopefully we just missed something :)

**Comment by TekExplorer** [comment]
Forgot to mention, turning on cloudflare proxy fixed it for him.

**Comment by Likqez** [comment]
**Solved** the issue with the help of this [issue](https://github.com/cskujawa/pterodactyl-single-server-docker-compose).

> ./game-servers/wings/data/wings/etc/config.yml :
> This file is a little weird, when you get the Panel up and running and create the location then the node, it generates a config for you which you're intended to paste into this file, when you first start panel (if everything works) it will fill in the rest of the file for you. That being said there was a few thigns I had to manually configure to get everything working.
    At the bottom there is these two settings
        allowed_origins:
        - https://panel.example.com/
        - https://172.30.0.1/16
        allow_cors_private_network: true

 After I pasted the configuration from the panel, and added
  ```
 allowed_origins:
- https://dev-panel.pluginstube.dev
allow_cors_private_network: true
 ```
and restarted wings. It all worked.
