### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by TekExplorer** [EdyTheCow/pterodactyl-docker#6]
Two things
1. you should update the image version to v0.7.18
2. maybe look into the upcoming v1.0 release?

**Comment by EdyTheCow** [comment]
I'm waiting for release of v1.0 since a lot of the guide and setup will have to be re-done.

**Comment by TekExplorer** [comment]
Makes sense. No reason not to update to .7.18 at least.

**Comment by EdyTheCow** [comment]
Updated to v1.x. Tested the setup in production environment without any issues. Docs are now also updated to match new setup.
