### ISSUE TITLE
Weird issue the pathing and certificates

### ISSUE THREAD

**Issue by SGTGunner** [EdyTheCow/pterodactyl-docker#8]
I finally got around to doing some updates and notice some weird behaviour.

The first was that SSL is working fine on blah.domain.com and also blah.domain.com/admin for the panel.
However, at the next level, such as blah.domain.com/admin/nodes it does not have SSL. I also notice in the logs on panel that I am also getting 401 errors as well. 

Going to investigate it more. But posting here is see if anyone has come across it?

**Comment by SGTGunner** [comment]
Closing the issue. Found what it was. It appears to be mixed content behind a proxy.
Once you set the `TRUSTED_PROXIES=*` in the `.env` file all works fine. I did not realize I still needed this for the version 1.0 of the panel.

**Comment by EdyTheCow** [comment]
That's weird, I don't have the `TRUSTED_PROXIES=*` defined in my current setup running the identical config from repo and I never came across such issue. Are you using the .env file from repo or your own? And are you using cloudflare or something else for SSL?

**Comment by SGTGunner** [comment]
I am using Let's Encyrpt. I am using your `.env` file though. So, It might be a side effect from that.
